name: NBA Betting Pregame Predictions

on:
  # NBA試合前に自動実行（バンクーバー/PDT夏時間に合わせて）
  schedule:
    # 平日試合用
    # バンクーバー時間 午後3:30 (UTC 22:30)
    - cron: '30 22 * * 1-5'
    
    # バンクーバー時間 午後4:30 (UTC 23:30)
    - cron: '30 23 * * 1-5'
    
    # バンクーバー時間 午後5:30 (UTC 00:30 翌日)
    - cron: '30 0 * * 2-6'
    
    # 週末試合用
    # バンクーバー時間 午前11:30 (UTC 18:30)
    - cron: '30 18 * * 0,6'
    
    # バンクーバー時間 午後2:30 (UTC 21:30)
    - cron: '30 21 * * 0,6'
    
    # バンクーバー時間 午後3:30 (UTC 22:30)
    - cron: '30 22 * * 0,6'
    
    # バンクーバー時間 午後5:30 (UTC 00:30 翌日)
    # 日曜の午後5:30 (月曜 00:30 UTC) と土曜の午後5:30 (日曜 00:30 UTC)
    - cron: '30 0 * * 0,1'
  
  # 手動トリガーも追加
  workflow_dispatch:

jobs:
  run-predictions:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # 30分でタイムアウト
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # 必要なパッケージを明示的にインストール
          pip install requests
      
      - name: Check environment
        run: |
          echo "Python version:"
          python --version
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Environment variables (safe ones only):"
          env | grep -v -E 'SECRET|TOKEN|PASSWORD|KEY'
          echo "SLACK_WEBHOOK_URL is set:" 
          if [ -n "$SLACK_WEBHOOK_URL" ]; then echo "Yes"; else echo "No"; fi
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      
      - name: Run betting model only
        id: model
        continue-on-error: true
        run: |
          echo "Running betting model..."
          python main.py -xgb -odds=bet365 -kc > betting_output.txt || echo "Model exited with error"
          echo "Betting model finished. Output size: $(wc -c < betting_output.txt) bytes"
      
      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          echo "Sending notification..."
          if [ -s betting_output.txt ]; then
            python send_notification.py betting_output.txt
          else
            echo "Warning: Empty output file. Running directly..."
            python send_notification.py --run-model
          fi